version: '3'
services:
  web:
    build: 
        context: ./web
    ports:
      - "8081:5000"
    volumes:
      - ./web:/code
    environment:
      FLASK_DEBUG: "true"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  mqtrw:
    build: 
        context: ./mqttrw
    depends_on:
      - redis
  prometheus:
    build:
        context: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web
  grafana:
    build:
      context: ./grafana
    ports:
     - '3000:3000'
#  mosquitto:
#    build: 
#        context: ./mosquitto
#    ports:
#      - 1883:1883
#      - 9001:9001   

