{
 "title": "fermctrlvar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "device", "query": "blank" }
  ]
 },
 "panels": [
  {
   "title": "Temperature actual and target for $device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "actual_temperature{device_name=\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "target_temperature{device_name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days of fermentation for $device",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_day{device_name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potentiometer value for $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "potentiometer_value{device_name=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}